// Geometric Tools Library
// https://www.geometrictools.com
// Copyright (c) 2025 Geometric Tools LLC
// Distributed under the Boost Software License, Version 1.0
// https://www.boost.org/LICENSE_1_0.txt
// File Version: 0.0.2025.10.29

#pragma once

// Top-level control over which tests are executed. The individual classes
// need unit testing.

//#define UT_UTILITY
#define UT_MATHEMATICS
//#define UT_MATHEMATICS_ALGEBRA
#define UT_MATHEMATICS_APPROXIMATION_2D
#define UT_MATHEMATICS_APPROXIMATION_3D
#define UT_MATHEMATICS_APPROXIMATION_ND
#define UT_MATHEMATICS_APPROXIMATION_POLYNOMIAL
//#define UT_MATHEMATICS_ARITHMETIC
//#define UT_MATHEMATICS_CONTAINMENT_2D
//#define UT_MATHEMATICS_CONTAINMENT_3D
//#define UT_MATHEMATICS_CONTAINMENT_ND
//#define UT_MATHEMATICS_CURVES
//#define UT_MATHEMATICS_DIFFERENTIALEQUATIONS
//#define UT_MATHEMATICS_DISTANCE_2D
//#define UT_MATHEMATICS_DISTANCE_3D
//#define UT_MATHEMATICS_DISTANCE_ND
//#define UT_MATHEMATICS_FUNCTIONS
//#define UT_MATHEMATICS_GEOMETRY_1D
//#define UT_MATHEMATICS_GEOMETRY_2D
//#define UT_MATHEMATICS_GEOMETRY_3D
//#define UT_MATHEMATICS_GEOMETRY_ND
//#define UT_MATHEMATICS_IMAGEPROCESSING
//#define UT_MATHEMATICS_INTEGRATION
//#define UT_MATHEMATICS_INTERPOLATION_1D
//#define UT_MATHEMATICS_INTERPOLATION_2D
//#define UT_MATHEMATICS_INTERPOLATION_3D
//#define UT_MATHEMATICS_INTERPOLATION_ND
//#define UT_MATHEMATICS_INTERSECTION_1D
//#define UT_MATHEMATICS_INTERSECTION_2D
//#define UT_MATHEMATICS_INTERSECTION_3D
//#define UT_MATHEMATICS_INTERSECTION_ND
//#define UT_MATHEMATICS_MATRIXANALYSIS
//#define UT_MATHEMATICS_MESHES
//#define UT_MATHEMATICS_MINIMIZERS
//#define UT_MATHEMATICS_MISCELLANEOUS
//#define UT_MATHEMATICS_PHYSICS
//#define UT_MATHEMATICS_PRIMITIVES_2D
//#define UT_MATHEMATICS_PRIMITIVES_3D
//#define UT_MATHEMATICS_PRIMITIVES_ND
//#define UT_MATHEMATICS_PROJECTION
//#define UT_MATHEMATICS_ROOTFINDERS
//#define UT_MATHEMATICS_SURFACES
//#define UT_MATHEMATICS_VOLUMES

// Utility
#if defined(UT_UTILITY)
#define UT_UTILITY_ATOMICMINMAX
#define UT_UTILITY_CONTAINERADAPTER
#define UT_UTILITY_HASHCOMBINE
#define UT_UTILITY_LATTICE
#define UT_UTILITY_MINHEAP
#define UT_UTILITY_MINIMUMSPANNINGTREE
#define UT_UTILITY_MULTIARRAY
#define UT_UTILITY_MULTIARRAYADAPTER
#define UT_UTILITY_RANGEITERATION
#define UT_UTILITY_RAWPTRCOMPARE
#define UT_UTILITY_SHAREDPTRCOMPARE
#define UT_UTILITY_STRINGUTILITY
#define UT_UTILITY_WEAKPTRCOMPARE
#endif

// Mathematics
#if defined(UT_MATHEMATICS)

// Mathematics/Algebra
#if defined(UT_MATHEMATICS_ALGEBRA)
#define UT_MATHEMATICS_AFFINETRANSFORM
#define UT_MATHEMATICS_AXISANGLE
#define UT_MATHEMATICS_CONVERTCOORDINATES
#define UT_MATHEMATICS_DUALQUATERNION
#define UT_MATHEMATICS_EULERANGLES
#define UT_MATHEMATICS_LIEGROUPSALGEBRAS
#define UT_MATHEMATICS_MATRIX
#define UT_MATHEMATICS_MATRIXACCESSOR
#define UT_MATHEMATICS_POLYNOMIAL
#define UT_MATHEMATICS_QUATERNION
#define UT_MATHEMATICS_RIGIDMOTION
#define UT_MATHEMATICS_VECTOR
#endif

// Mathematics/Approximation/2D
#if defined(UT_MATHEMATICS_APPROXIMATION_2D)
#define UT_MATHEMATICS_APPRCIRCLE2
#define UT_MATHEMATICS_APPRCURVEBYARCS
#define UT_MATHEMATICS_APPRELLIPSE2
#define UT_MATHEMATICS_APPRELLIPSEBYARCS
#define UT_MATHEMATICS_APPRHEIGHTLINE2
#define UT_MATHEMATICS_APPRORTHOGONALLINE2
#define UT_MATHEMATICS_APPRPARABOLA2
#define UT_MATHEMATICS_APPRPARALLELLINES2
#endif

// Mathematics/Approximation/3D
#if defined(UT_MATHEMATICS_APPROXIMATION_3D)
#define UT_MATHEMATICS_APPRCONE3
#define UT_MATHEMATICS_APPRCYLINDER3
#define UT_MATHEMATICS_APPRELLIPSOID3
#define UT_MATHEMATICS_APPRGREATARC3
#define UT_MATHEMATICS_APPRGREATCIRCLE3
#define UT_MATHEMATICS_APPRHEIGHTPLANE3
#define UT_MATHEMATICS_APPRHELMERTTRANSFORMATION3
#define UT_MATHEMATICS_APPRORTHOGONALLINE3
#define UT_MATHEMATICS_APPRORTHOGONALPLANE3
#define UT_MATHEMATICS_APPRPARABOLOID3
#define UT_MATHEMATICS_APPRSPHERE3
#define UT_MATHEMATICS_APPRTORUS3
#endif

// Mathematics/Approximation/ND
#if defined(UT_MATHEMATICS_APPROXIMATION_ND)
#define UT_MATHEMATICS_APPRGAUSSIANDISTRIBUTION
#endif

// Mathematics/Approximation/Polynomial
#if defined(UT_MATHEMATICS_APPROXIMATION_POLYNOMIAL)
//#define UT_MATHEMATICS_APPRPOLYNOMIAL
#define UT_MATHEMATICS_APPRPOLYNOMIAL1
//#define UT_MATHEMATICS_APPRPOLYNOMIAL2
//#define UT_MATHEMATICS_APPRPOLYNOMIAL3
#endif

// Mathematices/Arithmetic
#if defined(UT_MATHEMATICS_ARITHMETIC)
#define UT_MATHEMATICS_APCONVERSION
#define UT_MATHEMATICS_APINTERVAL
#define UT_MATHEMATICS_BITHACKS
#define UT_MATHEMATICS_BSNUMBER
#define UT_MATHEMATICS_BSPRECISION
#define UT_MATHEMATICS_BSRATIONAL
#define UT_MATHEMATICS_CONSTANTS
#define UT_MATHEMATICS_IEEEBINARY
#define UT_MATHEMATICS_IEEEBINARY16
#define UT_MATHEMATICS_IEEEFUNCTIONS
#define UT_MATHEMATICS_QFNUMBER
#define UT_MATHEMATICS_SWINTERVAL
#define UT_MATHEMATICS_UINTEGERALU32
#define UT_MATHEMATICS_UINTEGERAP32
#define UT_MATHEMATICS_UINTEGERFP32
#endif

// Mathematics/Containment/2D
#if defined(UT_MATHEMATICS_CONTAINMENT_2D)
// #define UT_MATHEMATICS_CONTCIRCLE2
// #define UT_MATHEMATICS_CONTELLIPSE2
// #define UT_MATHEMATICS_CONTELLIPSE2MINCR
// #define UT_MATHEMATICS_CONTORIENTEDBOX2
// #define UT_MATHEMATICS_CONTPOINTINPOLYGON2
#define UT_MATHEMATICS_CONTSCRIBECIRCLE2
#endif

// Mathematics/Containment/3D
#if defined(UT_MATHEMATICS_CONTAINMENT_3D)
// #define UT_MATHEMATICS_CONTCAPSULE3
// #define UT_MATHEMATICS_CONTCYLINDER3
// #define UT_MATHEMATICS_CONTELLIPSOID3
// #define UT_MATHEMATICS_CONTELLIPSOID3MINCR
// #define UT_MATHEMATICS_CONTLOZENGE3
#define UT_MATHEMATICS_CONTORIENTEDBOX3
// #define UT_MATHEMATICS_CONTPOINTINPOLYHEDRON3
// #define UT_MATHEMATICS_CONTSCRIBECIRCLE3
// #define UT_MATHEMATICS_CONTSCRIBESPHERE3
// #define UT_MATHEMATICS_CONTSPHERE3
#define UT_MATHEMATICS_CONTTETRAHEDRON3
#endif

// Mathematics/Containment/ND
#if defined(UT_MATHEMATICS_CONTAINMENT_ND)
#define UT_MATHEMATICS_CONTALIGNEDBOX
// #define UT_MATHEMATICS_CONTCONE
#endif

// Mathematics/Curves
#if defined(UT_MATHEMATICS_CURVES)
#define UT_MATHEMATICS_BASISFUNCTION
#define UT_MATHEMATICS_BEZIERCURVE
#define UT_MATHEMATICS_BSPLINECURVE
#define UT_MATHEMATICS_BSPLINECURVEFIT
#define UT_MATHEMATICS_BSPLINEGEODESIC
#define UT_MATHEMATICS_ELLIPSOIDGEODESIC
#define UT_MATHEMATICS_FRENETFRAME
#define UT_MATHEMATICS_IMPLICITCURVE2
#define UT_MATHEMATICS_NATURALCUBICSPLINE
#define UT_MATHEMATICS_NATURALQUINTICSPLINE
#define UT_MATHEMATICS_NURBSCIRCLE
#define UT_MATHEMATICS_NURBSCURVE
#define UT_MATHEMATICS_PARAMETRICCURVE
#define UT_MATHEMATICS_POLYNOMIALCURVE
#define UT_MATHEMATICS_REPARAMETERIZEBYARCLENGTH
#define UT_MATHEMATICS_RIEMANNIANGEODESIC
#define UT_MATHEMATICS_TCBSPLINECURVE
#endif

// Mathematics/DifferentialEquations
#if defined(UT_MATHEMATICS_DIFFERENTIALEQUATIONS)
#define UT_MATHEMATICS_ODEEULER
#define UT_MATHEMATICS_ODEIMPLICITEULER
#define UT_MATHEMATICS_ODEMIDPOINT
#define UT_MATHEMATICS_ODERUNGEKUTTA4
#endif

// Mathematics/Distance/2D
#if defined(UT_MATHEMATICS_DISTANCE_2D)
#define UT_MATHEMATICS_DISTCIRCLE2CIRCLE2
#define UT_MATHEMATICS_DISTLINE2ALIGNEDBOX2
#define UT_MATHEMATICS_DISTLINE2ARC2
#define UT_MATHEMATICS_DISTLINE2CIRCLE2
#define UT_MATHEMATICS_DISTLINE2ORIENTEDBOX2
#define UT_MATHEMATICS_DISTLINE2TRIANGLE2
#define UT_MATHEMATICS_DISTPOINT2ARC2
#define UT_MATHEMATICS_DISTPOINT2CIRCLE2
#define UT_MATHEMATICS_DISTPOINT2PARALLELOGRAM2
#define UT_MATHEMATICS_DISTRAY2ALIGNEDBOX2
#define UT_MATHEMATICS_DISTRAY2ARC2
#define UT_MATHEMATICS_DISTRAY2CIRCLE2
#define UT_MATHEMATICS_DISTRAY2ORIENTEDBOX2
#define UT_MATHEMATICS_DISTRAY2TRIANGLE2
#define UT_MATHEMATICS_DISTSEGMENT2ALIGNEDBOX2
#define UT_MATHEMATICS_DISTSEGMENT2ARC2
#define UT_MATHEMATICS_DISTSEGMENT2CIRCLE2
#define UT_MATHEMATICS_DISTSEGMENT2ORIENTEDBOX2
#define UT_MATHEMATICS_DISTSEGMENT2TRIANGLE2
#endif

// Mathematics/Distance/3D
#if defined(UT_MATHEMATICS_DISTANCE_3D)
#define UT_MATHEMATICS_DISTALIGNEDBOX3ORIENTEDBOX3
#define UT_MATHEMATICS_DISTCIRCLE3CIRCLE3
#define UT_MATHEMATICS_DISTLINE3ALIGNEDBOX3
#define UT_MATHEMATICS_DISTLINE3ARC3
#define UT_MATHEMATICS_DISTLINE3CANONICALBOX3
#define UT_MATHEMATICS_DISTLINE3CIRCLE3
#define UT_MATHEMATICS_DISTLINE3ORIENTEDBOX3
#define UT_MATHEMATICS_DISTLINE3RECTANGLE3
#define UT_MATHEMATICS_DISTLINE3TRIANGLE3
#define UT_MATHEMATICS_DISTLINEARCIRCULARSUPPORT3
#define UT_MATHEMATICS_DISTORIENTEDBOX3CONE3
#define UT_MATHEMATICS_DISTORIENTEDBOX3ORIENTEDBOX3
#define UT_MATHEMATICS_DISTPLANE3ALIGNEDBOX3
#define UT_MATHEMATICS_DISTPLANE3CANONICALBOX3
#define UT_MATHEMATICS_DISTPLANE3ORIENTEDBOX3
#define UT_MATHEMATICS_DISTPOINT3ARC3
#define UT_MATHEMATICS_DISTPOINT3CIRCLE3
#define UT_MATHEMATICS_DISTPOINT3CONVEXPOLYHEDRON3
#define UT_MATHEMATICS_DISTPOINT3CYLINDER3
#define UT_MATHEMATICS_DISTPOINT3FRUSTUM3
#define UT_MATHEMATICS_DISTPOINT3PARALLELEPIPED3
#define UT_MATHEMATICS_DISTPOINT3TETRAHEDRON3
#define UT_MATHEMATICS_DISTRAY3ALIGNEDBOX3
#define UT_MATHEMATICS_DISTRAY3ARC3
#define UT_MATHEMATICS_DISTRAY3CANONICALBOX3
#define UT_MATHEMATICS_DISTRAY3CIRCLE3
#define UT_MATHEMATICS_DISTRAY3ORIENTEDBOX3
#define UT_MATHEMATICS_DISTRAY3RECTANGLE3
#define UT_MATHEMATICS_DISTRAY3TRIANGLE3
#define UT_MATHEMATICS_DISTRECTANGLE3ALIGNEDBOX3
#define UT_MATHEMATICS_DISTRECTANGLE3CANONICALBOX3
#define UT_MATHEMATICS_DISTRECTANGLE3ORIENTEDBOX3
#define UT_MATHEMATICS_DISTRECTANGLE3RECTANGLE3
#define UT_MATHEMATICS_DISTSEGMENT3ALIGNEDBOX3
#define UT_MATHEMATICS_DISTSEGMENT3ARC3
#define UT_MATHEMATICS_DISTSEGMENT3CANONICALBOX3
#define UT_MATHEMATICS_DISTSEGMENT3CIRCLE3
#define UT_MATHEMATICS_DISTSEGMENT3ORIENTEDBOX3
#define UT_MATHEMATICS_DISTSEGMENT3RECTANGLE3
#define UT_MATHEMATICS_DISTSEGMENT3TRIANGLE3
#define UT_MATHEMATICS_DISTTETRAHEDRON3TETRAHEDRON3
#define UT_MATHEMATICS_DISTTRIANGLE3ALIGNEDBOX3
#define UT_MATHEMATICS_DISTTRIANGLE3CANONICALBOX3
#define UT_MATHEMATICS_DISTTRIANGLE3ORIENTEDBOX3
#define UT_MATHEMATICS_DISTTRIANGLE3TRIANGLE3
#define UT_MATHEMATICS_DISTTRIANGLE3RECTANGLE3
#endif

// Mathematics/Distance/ND
#if defined(UT_MATHEMATICS_DISTANCE_ND)
#define UT_MATHEMATICS_DISTALIGNEDBOXALIGNEDBOX
#define UT_MATHEMATICS_DISTLINELINE
#define UT_MATHEMATICS_DISTLINERAY
#define UT_MATHEMATICS_DISTLINESEGMENT
#define UT_MATHEMATICS_DISTPOINTALIGNEDBOX
#define UT_MATHEMATICS_DISTPOINTCANONICALBOX
#define UT_MATHEMATICS_DISTPOINTHYPERELLIPSOID
#define UT_MATHEMATICS_DISTPOINTHYPERPLANE
#define UT_MATHEMATICS_DISTPOINTLINE
#define UT_MATHEMATICS_DISTPOINTORIENTEDBOX
#define UT_MATHEMATICS_DISTPOINTRAY
#define UT_MATHEMATICS_DISTPOINTRECTANGLE
#define UT_MATHEMATICS_DISTPOINTSEGMENT
#define UT_MATHEMATICS_DISTPOINTTRIANGLE
#define UT_MATHEMATICS_DISTRAYRAY
#define UT_MATHEMATICS_DISTRAYSEGMENT
#define UT_MATHEMATICS_DISTSEGMENTSEGMENT
#endif

// Mathematics/Functions
#if defined(UT_MATHEMATICS_FUNCTIONS)
#define UT_MATHEMATICS_ACOSESTIMATE
#define UT_MATHEMATICS_ASINESTIMATE
#define UT_MATHEMATICS_ATANESTIMATE
#define UT_MATHEMATICS_CHEBYSHEVRATIO
#define UT_MATHEMATICS_CHEBYSHEVRATIOESTIMATE
#define UT_MATHEMATICS_COSESTIMATE
#define UT_MATHEMATICS_EXP2ESTIMATE
#define UT_MATHEMATICS_EXPESTIMATE
#define UT_MATHEMATICS_LOG2ESTIMATE
#define UT_MATHEMATICS_INVSQRTESTIMATE
#define UT_MATHEMATICS_LOGESTIMATE
#define UT_MATHEMATICS_REMEZALGORITHM
#define UT_MATHEMATICS_ROTATIONESTIMATE
#define UT_MATHEMATICS_SINESTIMATE
#define UT_MATHEMATICS_SLERP
#define UT_MATHEMATICS_SLERPESTIMATE
#define UT_MATHEMATICS_SQRTESTIMATE
#define UT_MATHEMATICS_TANESTIMATE
#endif

// Mathematics/Geometry/1D
#if defined(UT_MATHEMATICS_GEOMETRY_1D)
#define UT_MATHEMATICS_DISJOINTINTERVALS
#define UT_MATHEMATICS_EXACTSIGNDETERMINANT2
#define UT_MATHEMATICS_EXACTSIGNDETERMINANT3
#define UT_MATHEMATICS_EXACTSIGNDETERMINANT4
#endif

// Mathematics/Geometry/2D
#if defined(UT_MATHEMATICS_GEOMETRY_2D)
#define UT_MATHEMATICS_BSPPOLYGON2
#define UT_MATHEMATICS_CONSTRAINEDDELAUNAY2
#define UT_MATHEMATICS_CONVEXHULL2
#define UT_MATHEMATICS_CONVEXHULLSIMPLEPOLYGON
#define UT_MATHEMATICS_DELAUNAY2
#define UT_MATHEMATICS_DISJOINTRECTANGLES
#define UT_MATHEMATICS_EXACTCOLINEAR2
#define UT_MATHEMATICS_EXACTTOCIRCUMCIRCLE2
#define UT_MATHEMATICS_EXACTTOLINE2
#define UT_MATHEMATICS_EXACTTOLINEEXTENDED2
#define UT_MATHEMATICS_EXACTTOTRIANGLE2
#define UT_MATHEMATICS_INCREMENTALDELAUNAY2
// #define UT_MATHEMATICS_ISPLANARGRAPH
// #define UT_MATHEMATICS_MINIMALCYCLEBASIS
#define UT_MATHEMATICS_MINIMUMAREABOX2
// #define UT_MATHEMATICS_MINIMUMAREACIRCLE2
#define UT_MATHEMATICS_MINIMUMWIDTHPOINTS2
#define UT_MATHEMATICS_POLYGONTREE
#define UT_MATHEMATICS_POLYGONWINDINGORDER
#define UT_MATHEMATICS_ROTATINGCALIPERS
// #define UT_MATHEMATICS_SEPARATEPOINTS2
#define UT_MATHEMATICS_TRIANGULATECDT
// #define UT_MATHEMATICS_TRIANGULATEEC
#endif

// Mathematics/Geometry/3D
#if defined(UT_MATHEMATICS_GEOMETRY_3D)
// #define UT_MATHEMATICS_ALIGNEDBOXBV
// #define UT_MATHEMATICS_ALIGNEDBOXTREEOFPOINTS
// #define UT_MATHEMATICS_ALIGNEDBOXTREEOFSEGMENTS
// #define UT_MATHEMATICS_ALIGNEDBOXTREEOFTRIANGLES
// #define UT_MATHEMATICS_CONFORMALMAPGENUS0
#define UT_MATHEMATICS_CONVEXHULL3
#define UT_MATHEMATICS_DELAUNAY3
#define UT_MATHEMATICS_EXACTCOLINEAR3
#define UT_MATHEMATICS_EXACTCOPLANAR3
#define UT_MATHEMATICS_EXACTTOCIRCUMSPHERE3
#define UT_MATHEMATICS_EXACTTOPLANE3
#define UT_MATHEMATICS_EXACTTOTETRAHEDRON3
// #define UT_MATHEMATICS_EXTREMALQUERY3BSP
// #define UT_MATHEMATICS_EXTREMALQUERY3PRJ
// #define UT_MATHEMATICS_GENERATEMESHUV
// #define UT_MATHEMATICS_MINIMUMVOLUMEBOX3
// #define UT_MATHEMATICS_MINIMUMVOLUMESPHERE3
// #define UT_MATHEMATICS_ORIENTEDBOXBV
// #define UT_MATHEMATICS_ORIENTEDBOXTREEOFPOINTS
// #define UT_MATHEMATICS_ORIENTEDBOXTREEOFSEGMENTS
// #define UT_MATHEMATICS_ORIENTEDBOXTREEOFTRIANGLES
// #define UT_MATHEMATICS_SEPARATEPOINTS3
// #define UT_MATHEMATICS_SPLITMESHBYPLANE
#endif

// Mathematics/Geometry/ND
#if defined(UT_MATHEMATICS_GEOMETRY_ND)
// #define UT_MATHEMATICS_CLODPOLYLINE
#endif

// Mathematics/ImageProcessing
#if defined(UT_MATHEMATICS_IMAGEPROCESSING)
// #define UT_MATHEMATICS_CURVATUREFLOW2
// #define UT_MATHEMATICS_CURVATUREFLOW3
// #define UT_MATHEMATICS_CURVEEXTRACTOR
// #define UT_MATHEMATICS_CURVEEXTRACTORSQUARES
// #define UT_MATHEMATICS_CURVEEXTRACTORTRIANGLES
// #define UT_MATHEMATICS_FASTGAUSSIANBLUR1
// #define UT_MATHEMATICS_FASTGAUSSIANBLUR2
// #define UT_MATHEMATICS_FASTGAUSSIANBLUR3
// #define UT_MATHEMATICS_FASTMARCH
// #define UT_MATHEMATICS_GAUSSIANBLUR2
// #define UT_MATHEMATICS_GAUSSIANBLUR3
// #define UT_MATHEMATICS_GRADIENTANISOTROPIC2
// #define UT_MATHEMATICS_GRADIENTANISOTROPIC3
// #define UT_MATHEMATICS_IMAGE2
// #define UT_MATHEMATICS_IMAGE3
// #define UT_MATHEMATICS_MARCHINGCUBES
// #define UT_MATHEMATICS_MORPHOLOGY
// #define UT_MATHEMATICS_MORPHOLOGY2
// #define UT_MATHEMATICS_MORPHOLOGY3
// #define UT_MATHEMATICS_PDEFILTER
// #define UT_MATHEMATICS_PDEFILTER1
// #define UT_MATHEMATICS_PDEFILTER2
// #define UT_MATHEMATICS_PDEFILTER3
#define UT_MATHEMATICS_RASTERIZE2
// #define UT_MATHEMATICS_RASTERIZE3
// #define UT_MATHEMATICS_SURFACEEXTRACTOR
// #define UT_MATHEMATICS_SURFACEEXTRACTORCUBES
// #define UT_MATHEMATICS_SURFACEEXTRACTORMC
// #define UT_MATHEMATICS_SURFACEEXTRACTORTETRAHEDRA
#endif

// Mathematics/Integration
#if defined(UT_MATHEMATICS_INTEGRATION)
#define UT_MATHEMATICS_INTGGAUSSIANQUADRATURE
#define UT_MATHEMATICS_INTGROMBERG
#define UT_MATHEMATICS_INTGTRAPEZOIDRULE
#endif

// Mathematics/Interpolation/1D
#if defined(UT_MATHEMATICS_INTERPOLATION_1D)
// #define UT_MATHEMATICS_INTPAKIMANONUNIFORM1
// #define UT_MATHEMATICS_INTPAKIMAUNIFORM1
#define UT_MATHEMATICS_INTPBSPLINEUNIFORM1
#define UT_MATHEMATICS_INTPHERMITECUBIC1
#define UT_MATHEMATICS_INTPHERMITEQUINTIC1
#endif

// Mathematics/Interpolation/2D
#if defined(UT_MATHEMATICS_INTERPOLATION_2D)
// #define UT_MATHEMATICS_INTPAKIMAUNIFORM2
#define UT_MATHEMATICS_INTPBSPLINEUNIFORM2
// #define UT_MATHEMATICS_INTPCUBIC2
#define UT_MATHEMATICS_INTPHERMITECUBIC2
#define UT_MATHEMATICS_INTPHERMITEQUINTIC2
// #define UT_MATHEMATICS_INTPLINEAR2
// #define UT_MATHEMATICS_INTPLINEARNONUNIFORM2
#define UT_MATHEMATICS_INTPQUADRATICNONUNIFORM2
#define UT_MATHEMATICS_INTPTHINPLATESPLINE2
// #define UT_MATHEMATICS_INTPVECTORFIELD2
#endif

// Mathematics/Interpolation/3D
#if defined(UT_MATHEMATICS_INTERPOLATION_3D)
// #define UT_MATHEMATICS_INTPAKIMAUNIFORM3
#define UT_MATHEMATICS_INTPBSPLINEUNIFORM3
// #define UT_MATHEMATICS_INTPCUBIC3
#define UT_MATHEMATICS_INTPHERMITECUBIC3
#define UT_MATHEMATICS_INTPHERMITEQUINTIC3
// #define UT_MATHEMATICS_INTPLINEAR3
// #define UT_MATHEMATICS_INTPLINEARNONUNIFORM3
// #define UT_MATHEMATICS_INTPSPHERE3
#define UT_MATHEMATICS_INTPTHINPLATESPLINE3
#endif

// Mathematics/Interpolation/ND
#if defined(UT_MATHEMATICS_INTERPOLATION_ND)
 #define UT_MATHEMATICS_INTPBSPLINEUNIFORM
#endif

// Mathematics/Intersection
#if defined(UT_MATHEMATICS_INTERSECTION_1D)
#define UT_MATHEMATICS_INTRINTERVALS
#endif

// Mathematics/Intersection/2D
#if defined(UT_MATHEMATICS_INTERSECTION_2D)
// #define UT_MATHEMATICS_INTRALIGNEDBOX2CIRCLE2
// #define UT_MATHEMATICS_INTRALIGNEDBOX2ORIENTEDBOX2
// #define UT_MATHEMATICS_INTRALIGNEDARC2ARC2
// #define UT_MATHEMATICS_INTRALIGNEDCIRCLE2ARC2
// #define UT_MATHEMATICS_INTRALIGNEDCIRCLE2CIRCLE2
#define UT_MATHEMATICS_INTRAREAELLIPSE2ELLIPSE2
#define UT_MATHEMATICS_INTRELLIPSE2ELLIPSE2
// #define UT_MATHEMATICS_INTRHALFSPACE2POLYGON2
// #define UT_MATHEMATICS_INTRLINE2ALIGNEDBOX2
// #define UT_MATHEMATICS_INTRLINE2ARC2
// #define UT_MATHEMATICS_INTRLINE2CIRCLE2
#define UT_MATHEMATICS_INTRLINE2LINE2
// #define UT_MATHEMATICS_INTRLINE2ORIENTEDBOX2
#define UT_MATHEMATICS_INTRLINE2RAY2
#define UT_MATHEMATICS_INTRLINE2SEGMENT2
#define UT_MATHEMATICS_INTRLINE2TRIANGLE2
// #define UT_MATHEMATICS_INTRORIENTEDBOX2CIRCLE2
// #define UT_MATHEMATICS_INTRORIENTEDBOX2CONE2
// #define UT_MATHEMATICS_INTRRAY2ALIGNEDBOX2
// #define UT_MATHEMATICS_INTRRAY2ARC2
// #define UT_MATHEMATICS_INTRRAY2CIRCLE2
// #define UT_MATHEMATICS_INTRRAY2ORIENTEDBOX2
#define UT_MATHEMATICS_INTRRAY2RAY2
#define UT_MATHEMATICS_INTRRAY2SEGMENT2
#define UT_MATHEMATICS_INTRRAY2TRIANGLE2
// #define UT_MATHEMATICS_INTRSEGMENT2ALIGNEDBOX2
// #define UT_MATHEMATICS_INTRSEGMENT2ARC2
// #define UT_MATHEMATICS_INTRSEGMENT2CIRCLE2
// #define UT_MATHEMATICS_INTRSEGMENT2ORIENTEDBOX2
#define UT_MATHEMATICS_INTRSEGMENT2SEGMENT2
#define UT_MATHEMATICS_INTRSEGMENT2TRIANGLE2
#define UT_MATHEMATICS_INTRTRIANGLE2TRIANGLE2
#endif

// Mathematics/Intersection/3D
#if defined(UT_MATHEMATICS_INTERSECTION_3D)
// #define UT_MATHEMATICS_INTRALIGNEDBOX3CONE3
// #define UT_MATHEMATICS_INTRALIGNEDBOX3CYLINDER3
// #define UT_MATHEMATICS_INTRALIGNEDBOX3ORIENTEDBOX3
#define UT_MATHEMATICS_INTRALIGNEDBOX3SPHERE3
// #define UT_MATHEMATICS_INTRCANONICALBOX3CYLINDER3
// #define UT_MATHEMATICS_INTRCAPSULE3CAPSULE3
// #define UT_MATHEMATICS_INTRCONVEXMESH3PLANE3
#define UT_MATHEMATICS_INTRCYLINDER3CYLINDER3
// #define UT_MATHEMATICS_INTRELLIPSOID3ELLIPSOID3
// #define UT_MATHEMATICS_INTRHALFSPACE3CAPSULE3
// #define UT_MATHEMATICS_INTRHALFSPACE3CYLINDER3
// #define UT_MATHEMATICS_INTRHALFSPACE3ELLIPSOID3
// #define UT_MATHEMATICS_INTRHALFSPACE3ORIENTEDBOX3
// #define UT_MATHEMATICS_INTRHALFSPACE3SEGMENT3
// #define UT_MATHEMATICS_INTRHALFSPACE3SPHERE3
// #define UT_MATHEMATICS_INTRHALFSPACE3TRIANGLE3
// #define UT_MATHEMATICS_INTRLINE3ALIGNEDBOX3
#define UT_MATHEMATICS_INTRLINE3CAPSULE3
// #define UT_MATHEMATICS_INTRLINE3CONE3
#define UT_MATHEMATICS_INTRLINE3CYLINDER3
#define UT_MATHEMATICS_INTRLINE3ELLIPSOID3
#define UT_MATHEMATICS_INTRLINE3ORIENTEDBOX3
#define UT_MATHEMATICS_INTRLINE3SPHERE3
#define UT_MATHEMATICS_INTRLINE3TRIANGLE3
// #define UT_MATHEMATICS_INTRORIENTEDBOX3CONE3
// #define UT_MATHEMATICS_INTRORIENTEDBOX3CYLINDER3
// #define UT_MATHEMATICS_INTRORIENTEDBOX3FRUSTUM3
// #define UT_MATHEMATICS_INTRORIENTEDBOX3ORIENTEDBOX3
#define UT_MATHEMATICS_INTRORIENTEDBOX3SPHERE3
// #define UT_MATHEMATICS_INTRPLANE3CAPSULE3
#define UT_MATHEMATICS_INTRPLANE3CIRCLE3
#define UT_MATHEMATICS_INTRPLANE3CYLINDER3
// #define UT_MATHEMATICS_INTRPLANE3ELLIPSOID3
// #define UT_MATHEMATICS_INTRPLANE3ORIENTEDBOX3
#define UT_MATHEMATICS_INTRPLANE3PLANE3
// #define UT_MATHEMATICS_INTRPLANE3SPHERE3
// #define UT_MATHEMATICS_INTRPLANE3TRIANGLE3
#define UT_MATHEMATICS_INTRRAY3ALIGNEDBOX3
#define UT_MATHEMATICS_INTRRAY3CAPSULE3
// #define UT_MATHEMATICS_INTRRAY3CONE3
#define UT_MATHEMATICS_INTRRAY3CYLINDER3
#define UT_MATHEMATICS_INTRRAY3ELLIPSOID3
#define UT_MATHEMATICS_INTRRAY3ORIENTEDBOX3
#define UT_MATHEMATICS_INTRRAY3SPHERE3
#define UT_MATHEMATICS_INTRRAY3TRIANGLE3
#define UT_MATHEMATICS_INTRSEGMENT3ALIGNEDBOX3
#define UT_MATHEMATICS_INTRSEGMENT3CAPSULE3
// #define UT_MATHEMATICS_INTRSEGMENT3CONE3
#define UT_MATHEMATICS_INTRSEGMENT3CYLINDER3
#define UT_MATHEMATICS_INTRSEGMENT3ELLIPSOID3
#define UT_MATHEMATICS_INTRSEGMENT3ORIENTEDBOX3
#define UT_MATHEMATICS_INTRSEGMENT3SPHERE3
#define UT_MATHEMATICS_INTRSEGMENT3TRIANGLE3
// #define UT_MATHEMATICS_INTRSPHERE3CONE3
// #define UT_MATHEMATICS_INTRSPHERE3FRUSTUM3
// #define UT_MATHEMATICS_INTRSPHERE3SPHERE3
// #define UT_MATHEMATICS_INTRSPHERE3TRIANGLE3
// #define UT_MATHEMATICS_INTRTETRAHEDRON3TETRAHEDRON3
#define UT_MATHEMATICS_INTRTRIANGLE3CYLINDER3
// #define UT_MATHEMATICS_INTRTRIANGLE3ORIENTEDBOX3
#define UT_MATHEMATICS_INTRTRIANGLE3TRIANGLE3
#endif

// Mathematics/Intersection/ND
#if defined(UT_MATHEMATICS_INTERSECTION_ND)
#define UT_MATHEMATICS_INTRALIGNEDBOXALIGNEDBOX
#define UT_MATHEMATICS_INTRCONVEXPOLYGONHYPERPLANE
// #define UT_MATHEMATICS_INTRLINEHYPERPLANE
// #define UT_MATHEMATICS_INTRRAYHYPERPLANE
// #define UT_MATHEMATICS_INTRSEGMENTHYPERPLANE
#endif

// Mathematics/MatrixAnalysis
#if defined(UT_MATHEMATICS_MATRIXANALYSIS)
#define UT_MATHEMATICS_BANDEDMATRIX
#define UT_MATHEMATICS_BLOCKCHOLESKYDECOMPOSITION
#define UT_MATHEMATICS_BLOCKLDLTDECOMPOSITION
#define UT_MATHEMATICS_CHOLESKYDECOMPOSITION
#define UT_MATHEMATICS_GAUSSIANELIMINATION
#define UT_MATHEMATICS_LDLTDECOMPOSITION
#define UT_MATHEMATICS_LINEARSYSTEM
#define UT_MATHEMATICS_SINGULARVALUEDECOMPOSITION
#define UT_MATHEMATICS_SYMMETRICEIGENSOLVER
#endif

// Mathematics/Meshes
#if defined(UT_MATHEMATICS_MESHES)
#define UT_MATHEMATICS_DYNAMICETMANIFOLDMESH
// #define UT_MATHEMATICS_DYNAMICETNONMANIFOLDMESH
#define UT_MATHEMATICS_DYNAMICTSMANIFOLDMESH
#define UT_MATHEMATICS_DYNAMICVETMANIFOLDMESH
// #define UT_MATHEMATICS_DYNAMICVETNONMANIFOLDMESH
// #define UT_MATHEMATICS_DYNAMICVTSMANIFOLDMESH
#define UT_MATHEMATICS_EDGEKEY
#define UT_MATHEMATICS_FEATUREKEY
#define UT_MATHEMATICS_INDEXATTRIBUTE
#define UT_MATHEMATICS_MESH
// #define UT_MATHEMATICS_MESHCURVATURE
// #define UT_MATHEMATICS_MESHSMOOTHER
#define UT_MATHEMATICS_PLANARMESH
// #define UT_MATHEMATICS_RECTANGLEMESH
#define UT_MATHEMATICS_RECTANGLEPATCHMESH
#define UT_MATHEMATICS_STATICVETMANIFOLDMESH
// #define UT_MATHEMATICS_STATICVTSMANIFOLDMESH
#define UT_MATHEMATICS_TETRAHEDRONKEY
#define UT_MATHEMATICS_TRIANGLEKEY
#define UT_MATHEMATICS_TUBEMESH
#define UT_MATHEMATICS_UNIQUEVERTICESSIMPLICES
#define UT_MATHEMATICS_VERTEXATTRIBUTE
// #define UT_MATHEMATICS_VERTEXCOLLAPSEMESH
#define UT_MATHEMATICS_VETFEATURESKS
#define UT_MATHEMATICS_VETMANIFOLDMESHKS
#endif

// Mathematics/Minimizers
#if defined(UT_MATHEMATICS_MINIMIZERS)
#define UT_MATHEMATICS_BRENTSMINIMIZER
#define UT_MATHEMATICS_GAUSSNEWTONMINIMIZER
#define UT_MATHEMATICS_LCPSOLVER
#define UT_MATHEMATICS_LEVENBERGMARQUARDTMINIMIZER
#define UT_MATHEMATICS_POWELLSMINIMIZER
#endif

// Mathematics/Miscellaneous
#if defined(UT_MATHEMATICS_MISCELLANEOUS)
#define UT_MATHEMATICS_CIRCLETHROUGHPOINTSPECIFIEDTANGENTANDRADIUS
#define UT_MATHEMATICS_CIRCLETHROUGHTWOPOINTSSPECIFIEDRADIUS
#define UT_MATHEMATICS_INSCRIBEDFIXEDASPECTRECTINQUAD
#define UT_MATHEMATICS_RANDOMPOINTONHYPERSPHERE
// #define UT_MATHEMATICS_SORTPOINTSONCIRCLE
#define UT_MATHEMATICS_STLBINARYFILE
#endif

// Mathematics/Physics
#if defined(UT_MATHEMATICS_PHYSICS)
#define UT_MATHEMATICS_BOXMANAGER
#define UT_MATHEMATICS_MASSSPRINGARBITRARY
#define UT_MATHEMATICS_MASSSPRINGCURVE
#define UT_MATHEMATICS_MASSSPRINGSURFACE
#define UT_MATHEMATICS_MASSSPRINGVOLUME
#define UT_MATHEMATICS_PARTICLESYSTEM
#define UT_MATHEMATICS_POLYHEDRALMASSPROPERTIES
#define UT_MATHEMATICS_RECTANGLEMANAGER
#define UT_MATHEMATICS_RIGIDBODY
#endif

// Mathematics/Primitives/2D
#if defined(UT_MATHEMATICS_PRIMITIVES_2D)
#define UT_MATHEMATICS_ARC2
#define UT_MATHEMATICS_PARALLELOGRAM2
#define UT_MATHEMATICS_POLYGON2
#endif

// Mathematics/Primitives/3D
#if defined(UT_MATHEMATICS_PRIMITIVES_3D)
#define UT_MATHEMATICS_ARC3
#define UT_MATHEMATICS_CIRCLE3
#define UT_MATHEMATICS_CONVEXMESH3
#define UT_MATHEMATICS_CONVEXPOLYHEDRON3
#define UT_MATHEMATICS_ELLIPSE3
#define UT_MATHEMATICS_FRUSTUM3
#define UT_MATHEMATICS_PARALLELEPIPED3
#define UT_MATHEMATICS_POLYHEDRON3
#define UT_MATHEMATICS_TETRAHEDRON3
#define UT_MATHEMATICS_TORUS3
#endif

// Mathematics/Primitives/ND
#if defined(UT_MATHEMATICS_PRIMITIVES_ND)
#define UT_MATHEMATICS_ALIGNEDBOX
#define UT_MATHEMATICS_CANONICALBOX
#define UT_MATHEMATICS_CAPSULE
#define UT_MATHEMATICS_CONE
#define UT_MATHEMATICS_CYLINDER
#define UT_MATHEMATICS_HALFSPACE
#define UT_MATHEMATICS_HYPERELLIPSOID
#define UT_MATHEMATICS_HYPERPLANE
#define UT_MATHEMATICS_HYPERSPHERE
#define UT_MATHEMATICS_LINE
#define UT_MATHEMATICS_LOZENGE
#define UT_MATHEMATICS_ORIENTEDBOX
#define UT_MATHEMATICS_RAY
#define UT_MATHEMATICS_RECTANGLE
#define UT_MATHEMATICS_SEGMENT
#define UT_MATHEMATICS_SEGMENTMESH
#define UT_MATHEMATICS_TRIANGLE
#endif

// Mathematics/Projection
#if defined(UT_MATHEMATICS_PROJECTION)
#define UT_MATHEMATICS_PROJECTELLIPSOIDTOPLANE
#define UT_MATHEMATICS_PROJECTHYPERELLIPSOIDTOLINE
#define UT_MATHEMATICS_PROJECTPOINTSTOCOORDINATEPLANE
#endif

// Mathematics/RootFinders
#if defined(UT_MATHEMATICS_ROOTFINDERS)
#define UT_MATHEMATICS_POLYNOMIALROOT
#define UT_MATHEMATICS_ROOTSBISECTION1
#define UT_MATHEMATICS_ROOTSBISECTION2
#define UT_MATHEMATICS_ROOTSBRENTSMETHOD
#define UT_MATHEMATICS_ROOTSCUBIC
#define UT_MATHEMATICS_ROOTSGENERALPOLYNOMIAL
#define UT_MATHEMATICS_ROOTSLINEAR
#define UT_MATHEMATICS_ROOTSPOLYNOMIAL
#define UT_MATHEMATICS_ROOTSQUADRATIC
#define UT_MATHEMATICS_ROOTSQUARTIC
#endif

// Mathematics/Surfaces
#if defined(UT_MATHEMATICS_SURFACES)
#define UT_MATHEMATICS_BSPLINESURFACE
#define UT_MATHEMATICS_BSPLINESURFACEFIT
#define UT_MATHEMATICS_DARBOUXFRAME
#define UT_MATHEMATICS_IMPLICITSURFACE3
#define UT_MATHEMATICS_NURBSSPHERE
#define UT_MATHEMATICS_NURBSSURFACE
#define UT_MATHEMATICS_PARAMETRICSURFACE
#define UT_MATHEMATICS_QUADRICSURFACE
#endif

// Mathematics/Volumes
#if defined(UT_MATHEMATICS_VOLUMES)
#define UT_MATHEMATICS_BSPLINEVOLUME
#define UT_MATHEMATICS_NURBSVOLUME
#define UT_MATHEMATICS_PARAMETRICVOLUME
#endif

#endif
